site_name: Single Worm Imaging - Analysis Template
# site_url: TO-DO
# repo_url: TO-DO
# repo_name: TO-DO
copyright: Copyright &copy; 2025, Friedrich Miescher Institute for Biomedical Research (FMI), Basel (Switzerland)
extra_css:
  - css/extra.css
nav:
  - Home: index.md
  - Installation: installation.md
  - Data: data.md
  - Tutorial:
    - 'Tutorials': tutorial/tutorials.md
  - 'How-to Guide':
    - 'Prepare sample': how_to/Sample_preparation.md
    - 'Microscope aquisition': how_to/Microscope_aquisition.md
    - 'Run Workflow': how_to/run_workflow.md
    - 'Setup analysis': how_to/Analysis_environment_setup.md
    - 'Train Segmentation Model': how_to/train_network.md
  - Explanation:
    - 'Explanations': explanation/explanations.md
  - References:
    - References: references/references.md
  - Imprint: imprint.md
theme:
  name: material
  favicon: images/favicon.ico
  icon:
    repo:
      fontawesome/brands/github
  font:
    text: Source Sans Pro
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.footer
    - header.autohide
    - content.code.copy
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
extra_javascript:
  - javascripts/trigger_user_defined_values.js
plugins:
  - offline:
      enabled: !ENV [ OFFLINE, false ]  # noqa
#  - git-revision-date-localized:
#      enable_creation_date: true
#   - git-committers:
#       repository: TO-DO
#       branch: main
  - user-defined-values:
      keywords:
        DATASET:
          placeholder: dataset-name
        SLURM_ACCOUNT:
          placeholder: slurm-account
        MAIL_TO:
            placeholder: first.last@mail.me
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
