[project]
name = "Single Worm Imaging - Analysis Template"
version = "0.1.0"
description = "Add a short description here"
authors = [
    "Tim-Oliver Buchholz <tim-oliver.buchholz@fmi.ch>",
]
channels = ["nvidia", "conda-forge", "pytorch", "bioconda"]
platforms = ["linux-64", "win-64", "osx-arm64", "osx-64"]

[system-requirements]
# See https://pixi.sh/latest/features/system_requirements/#default-system-requirements

[tasks]
cache_status = "python -m faim_ipa.pixi.cache_status"
source_status = "python -m faim_ipa.pixi.src_status source"
log_commit = {cmd = 'python -m faim_ipa.pixi.log_commit $TASK', env = {TASK = ""}}

[tasks.link_dataset]
cmd = """
cd raw_data ;
ln -s $DATASET ;

"""
env = { DATASET = ""}

[tasks.config]
cmd = """
mkdir -p $WD ;
TASK=BUILD_CONFIG pixi run log_commit ;
cd $WD ;
python $PIXI_PROJECT_ROOT/source/build_config.py
"""
env = { WD = "runs/example"}
depends-on=["cache_status", "source_status"]

[tasks.convert_to_zarr]
cmd = """
TASK=CONVERT_TO_ZARR pixi run log_commit ;
cd $WD ;
python $PIXI_PROJECT_ROOT/source/s01_convert_to_zarr/run.py --config s01_convert_to_zarr_config.yaml
"""
env = { WD = "runs/example"}
depends-on=["cache_status", "source_status"]

[tasks.convert_to_zarr_slurm]
cmd = """
TASK=CONVERT_TO_ZARR_SLURM pixi run log_commit ;
sbatch --account $ACCOUNT $PIXI_PROJECT_ROOT/source/s01_convert_to_zarr/slurm-job_convert-to-zarr.sh $ACCOUNT $WD
"""
env = { WD = "runs/example", ACCOUNT = ""}
depends-on=["cache_status", "source_status"]

[tasks.submit_workflow]
cmd = """TASK=SUBMIT_WORKFLOW pixi run log_commit ;
sbatch --account $ACCOUNT $PIXI_PROJECT_ROOT/source/slurm-job_run-workflow.sh $ACCOUNT $MAIL $WD
"""
env = { ACCOUNT = "", MAIL = "", WD = "runs/example"}
depends-on=["cache_status", "source_status"]

[tasks.prepare_annotation_data_config]
cmd = """
mkdir -p $WD ;
TASK=BUILD_ANNOTATION_DATA_CONFIG pixi run log_commit ;
cd $WD ;
python $PIXI_PROJECT_ROOT/source/s02_segment/annotation_data_config.py
"""
env = { WD = "runs/example"}
depends-on=["cache_status", "source_status"]
outputs = ["prepare_training_data_config.yaml"]

[tasks.prepare_annotation_data_slurm]
cmd = """
TASK=PREPARE_ANNOTATION_DATA_SLURM pixi run log_commit ;
sbatch --account $ACCOUNT $PIXI_PROJECT_ROOT/source/s02_segment/slurm-job-prepare-annotation-data.sh $WD
"""
env = { WD = "runs/example", ACCOUNT=""}
depends-on=["cache_status", "source_status", "prepare_annotation_data_config"]

[dependencies]
python = ">=3.12.9,<3.14"
faim-ipa = ">=0.13.0,<0.14"
pandas = ">=2.2.3,<3"
dask = ">=2025.3.0,<2026"
numcodecs = ">=0.15.1,<0.16"
ome-zarr = ">=0.10.3,<0.11"
numpy = ">=2.2.4,<3"
rich = ">=13.9.4,<14"

[feature.docs.dependencies]
mkdocs = ">=1.6.0,<2"
mkdocs-git-committers-plugin-2 = ">=2.3.0,<3"
mkdocs-git-revision-date-localized-plugin = ">=1.2.6,<2"
mkdocs-material = ">=9.5.31,<10"
mkdocstrings = ">=0.25.2,<0.26"

[feature.docs.tasks]
clean_docs = "rm -rf site"
build_docs = { cmd ="OFFLINE=TRUE mkdocs build", depends-on=["clean_docs"] }
show_docs = "mkdocs serve"

[feature.dev.dependencies]
pre-commit = ">=3.1.1,<3.8"

[feature.dev.tasks]
install_hooks = "pre-commit install"
lint = { cmd="pre-commit run --all-files", depends-on=["install_hooks"] }

[feature.jupyter.dependencies]
jupyter = ">=1.0.0,<1.1"
napari = ">=0.5.0,<0.6"
pyqt = ">=5.15.9,<6"
ipyfilechooser = ">=0.6.0,<0.7"

[feature.jupyter.tasks]
jupyter = "NAPARI_ASYNC=1 jupyter lab"
napari = "NAPARI_ASYNC=1 napari"

[feature.jupyter.tasks.create_selection]
cmd = """
TASK=CREATE_SELECTION pixi run log_commit ;
cp $PIXI_PROJECT_ROOT/source/s01_convert_to_zarr/Create_Selection.ipynb $WD ;
cd $WD ;
pixi run "jupyter lab" Create_Selection.ipynb
"""
env = { WD = "runs/example"}
depends-on=["cache_status", "source_status"]

[feature.jupyter.tasks.visualize_raw]
cmd = """
TASK=VISUALIZE_RAW pixi run log_commit ;
cp $PIXI_PROJECT_ROOT/source/s01_convert_to_zarr/Visualize-Raw-Data.ipynb $WD ;
cd $WD ;
pixi run "jupyter lab" Visualize-Raw-Data.ipynb
"""
env = { WD = "runs/example"}
depends-on=["cache_status", "source_status"]

[feature.nbdev.dependencies]
nbdev = ">=2.2.10,<2.3"
setuptools = ">=75.8.2,<76"

[feature.nbdev.tasks]
clean = "nbdev_clean --clear_all"

[feature.nextflow.target.linux-64.dependencies]
nextflow = ">=24.10.5,<25"

[feature.nextflow]
system-requirements = {linux="4.18"}

[feature.nextflow.tasks.workflow_slurm]
cmd = """
TASK=WORKFLOW_SLURM pixi run log_commit ;
cd $WD ;
nextflow run $PIXI_PROJECT_ROOT/source/workflow.nf --convert_to_zarr_config $(pwd)/s01_convert_to_zarr_config.yaml --segmentation_config $(pwd)/s02_segmentation_config.yaml -profile slurm -with-report -resume -with-timeline -disable-jobs-cancellation -N $MAIL
"""
env = { WD = "runs/example", MAIL = ""}
depends-on = ["cache_status", "source_status"]

[feature.nextflow.tasks.clean_nf]
cmd = """
cd $WD ;
nextflow clean -f
"""
env = { WD = "runs/example" }
depends-on = ["cache_status"]

[feature.worm-segmentation.dependencies]
pytorch-lightning = ">=2.3.0,<2.4"
pytorch = {version=">=2.4,<2.5", channel="pytorch"}
monai = ">=1.3.1,<1.4"
h5py = ">=3.11.0,<3.12"
opencv = ">=4.10.0,<4.11"
ignite = "*"
tensorboard = ">=2.17.0,<2.18"

[feature.worm-segmentation.tasks.train_model]
cmd = """
TASK=TRAIN_MODEL pixi run log_commit ;
cd $WD ;
pixi run python $PIXI_PROJECT_ROOT/source/s02_segment/train_network.py
"""
env = { WD = "runs/example"}
depends-on=["cache_status", "source_status"]

[feature.worm-segmentation.tasks.proof_read_dataset]
cmd = """
TASK=PROOF_READ_DATASET pixi run log_commit ;
cd $WD ;
pixi run python $PIXI_PROJECT_ROOT/source/s02_segment/proof_read_dataset.py
"""
env = { WD = "runs/example"}
depends-on=["cache_status", "source_status"]

[feature.micro-sam]
channels = ["nvidia", "pytorch", "conda-forge"]
system-requirements = {linux="4.18"}

[feature.micro-sam.dependencies]
python = "3.11.*"
napari = ">=0.5.0,<0.6"
micro_sam = ">=1.3.1,<1.4"
pyqt = ">=5.15.9,<6"
lxml-html-clean = ">=0.4.1,<0.5"
lxml = ">=4.9.2,<5"
ome-zarr = ">=0.10.3,<0.11"
faim-ipa = ">=0.13.0,<0.14"
pandas = ">=2.2.3,<3"
rich = ">=13.9.4,<14"
dask = ">=2024.8.1,<2025"
tifffile = ">=2024.4,<2024.6"
imagecodecs = {version="*", channel="conda-forge"}
libjpeg-turbo = {version="*", channel="conda-forge"}
numcodecs = ">=0.15.1,<0.16"

[feature.micro-sam.tasks.prepare_annotation_data]
cmd = """
TASK=PREPARE_ANNOTATION_DATA pixi run log_commit ;
cd $WD ;
pixi run python $PIXI_PROJECT_ROOT/source/s02_segment/prepare_annotation_data.py
"""
env = { WD = "runs/example"}
depends-on=["cache_status", "source_status"]

[feature.micro-sam.tasks.annotate_data]
cmd = """
pixi run micro_sam.annotator_3d -i $TIFF -e $EMBEDDING
"""
env = {TIFF = "", EMBEDDING = ""}

[feature.micro-sam.tasks.prepare_training_data]
cmd = """
TASK=PREPARE_TRAINING_DATA pixi run log_commit ;
cd $WD ;
pixi run python $PIXI_PROJECT_ROOT/source/s02_segment/prepare_training_data.py
"""
env = { WD = "runs/example"}
depends-on=["cache_status", "source_status"]

[feature.cuda]
platforms = ["linux-64"]

[feature.cuda.dependencies]
pytorch-cuda = {version="11.8.*", channel="pytorch"}

[feature.cuda.tasks.segmentation_gpu]
cmd = """
TASK=SEGMENTATION pixi run log_commit ;
cd $WD ;
pixi run python $PIXI_PROJECT_ROOT/source/s02_segment/run.py --config s02_segmentation_config.yaml --inputs s01_convert_to_zarr_result.yaml
"""
env = { WD = "runs/example"}
depends-on=["cache_status", "source_status"]

[feature.cuda.tasks.check_cuda]
cmd = 'python -c "import torch; print(torch.cuda.is_available())"'


[environments]
docs = { features = ["docs"], solve-group="default" }
dev = { features = ["dev"], solve-group="default" }
jupyter = { features = ["jupyter"], solve-group="default" }
nbdev = { features = ["nbdev"], no-default-feature = true}
nextflow = {features=["nextflow"], solve-group="default" }
worm-segmentation = {features=["worm-segmentation", "cuda"], solve-group="cuda" }
micro-sam-embedding = {features=["micro-sam", "cuda"], no-default-feature=true}
